# Basic Tensors

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
x = np.arange(0, 25)
x = tf.constant(x)
tf.square(x)

<tf.Tensor: id=2, shape=(25,), dtype=int32, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [6]:
x = tf.reshape(x,(5,5))
x

<tf.Tensor: id=6, shape=(5, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])>

In [9]:
tmp = tf.constant([1,2,3,4],shape=(2,2))
tmp

<tf.Tensor: id=12, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [14]:
#shape does not work with tf.Variable
try:
    # This will produce a ValueError
    tf.Variable([1,2,3,4], shape=(2,2))
except ValueError as v:
    # See what the ValueError says
    print(v)

The initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).


In [11]:
x = tf.cast(x, tf.float32)
x

<tf.Tensor: id=16, shape=(5, 5), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]], dtype=float32)>

In [12]:
#Broadcasting
y = tf.constant(2, shape=(5,5),dtype=tf.float32)
y

<tf.Tensor: id=19, shape=(5, 5), dtype=float32, numpy=
array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]], dtype=float32)>

In [13]:
result = tf.multiply(x, y)
result

<tf.Tensor: id=20, shape=(5, 5), dtype=float32, numpy=
array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.],
       [30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.]], dtype=float32)>